module.exports = {
    "parser": "babel-eslint",
    "extends": "airbnb",
    "globals": {
      "__DEV__": true,
      "expect": true
    },
    "rules": {
      "arrow-body-style": ["error", "as-needed"],
      "arrow-parens": ["error", "always"],
      "arrow-spacing": ["error", { "before": true, "after": true }],
      "babel/generator-star-spacing": 0,
      "babel/no-invalid-this": 1,
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
      "comma-dangle": ["error", "always-multiline"],
      "comma-style": ["error", "last"],
      "computed-property-spacing": ["error", "never"],
      "consistent-return": "warn",
      "curly": "error",
      "eol-last": ["error", "always"],
      "eqeqeq": "error",
      "func-call-spacing": ["error", "never"],
      "func-names": 0,
      "function-paren-newline": [0],
      "import/prefer-default-export": 0,
      "import/no-webpack-loader-syntax": "warn",
      "import/no-named-as-default-member": "warn",
      "import/no-dynamic-require": 0,
      "import/no-commonjs": "warn",
      "import/no-extraneous-dependencies": 0,
      "import/no-unresolved": [2, { "ignore": ["^[~]", "^[@]", "^[&]"] }],
      "import/extensions": 0,
      "indent": ["error", 2, { "SwitchCase": 1 }],
      "jsx-a11y/alt-text": 0,
      "jsx-a11y/no-noninteractive-element-interactions": "warn",
      "jsx-a11y/no-redundant-roles": "warn",
      "jsx-a11y/no-static-element-interactions": 0,
      "jsx-a11y/label-has-for": 0,
      "jsx-a11y/label-has-associated-control": 0,
      "jsx-quotes": [2, "prefer-double"],
      "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
      "keyword-spacing": ["error", { "before": true, "after": true }],
      "max-len": [1, 120],
      "no-underscore-dangle": 0,
      "no-confusing-arrow": 0,
      "no-unused-vars": ["error", { "varsIgnorePattern": "Mixin" }],
      "no-useless-escape": 0,
      "no-trailing-spaces": "error",
      "no-unneeded-ternary": "error",
      "no-else-return": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": "error",
      "no-multi-assign": 0,
      "no-unused-expressions": 0,
      "no-invalid-this": 0,
      "no-multi-spaces": "error",
      "no-prototype-builtins": 0,
      "no-restricted-syntax": "warn",
      "object-curly-newline": ["error", { "consistent": true }],
      "operator-linebreak": 0,
      "padded-blocks": ["error", "never"],
      "prefer-const": "error",
      "prefer-object-spread": "warn",
      "radix": ["warn", "as-needed"],
      "react/jsx-filename-extension": 0,
      "react/no-danger": 0,
      "react/require-default-props": 0,
      "react/react-in-jsx-scope": "error",
      "react/forbid-prop-types": 0,
      "react/jsx-max-props-per-line": ["error", { "maximum": 1, "when": "multiline" }],
      "react/no-array-index-key" : 0,
      "react/no-string-refs": 0,
      "react/no-typos": "off",
      "react/no-unused-prop-types": "warn",
      "react/sort-prop-types": [1, { "ignoreCase": true }],
      "react-native/split-platform-components": 0,
      "rest-spread-spacing": "error",
      "semi": "error",
      "space-before-function-paren": ["error", { "anonymous": "never", "named": "never", "asyncArrow": "always" }],
      "space-infix-ops": "error",
      "wrap-iife": ["error", "any"],
      "yield-star-spacing": ["error", "after"],
    },
    "env": {
      "jest": true,
      "browser": true,
      "es6": true,
    },
    "plugins": [
      "babel",
      "json",
    ]
};
